#!/bin/sh
bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             25
bspc config left_padding            25
bspc config right_padding           25
bspc config bottom_padding          25
# bspc config border_radius           5

bspc config split_ratio             0.60
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc config active_border_color "#27303a"
bspc config normal_border_color "#27303a"
bspc config focused_border_color "#27303a"

bspc rule -a emacs manage=on
bspc rule -a surf manage=on
bspc rule -a icecat manage=on

bspc monitor -d . . . . . . . . . .

bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config focused_border_color "#000000"

