#!/bin/sh
R="#[fg=#a04630]"
Y="#[fg=#a09c30]"
G="#[fg=#30a06a]"
B="#[fg=#3064a0]"
D="#[fg=#110c0f]"

TAU=`date +'%d:%m/%H:%M'`
TAUTEXT="${B} ${TAU} "
CASS=`TZ=Asia/Manila date +'%d:%m/%H:%M'`
CHOUR=`TZ=Asia/Manila date +'%H'`
CDAY=`TZ=Asia/Manila date +'%u'`

CASSTIME=`[ $CHOUR -ge 8 ] && [ $CHOUR -le 23 ] && echo "${B} ${CASS} " || echo "${R} ${CASS} "`

BATT=`apm -l`
CHARGE=`apm -b`
LOWBATT=`[ $BATT -le 30 ] && echo "${R}" || echo "${G}"`
CHARGING=`[ $CHARGE = 3 ] && echo "${B}" || echo "${LOWBATT}"`

TODO=`todo`
TODOTEXT=`[ -z $TODO ] || echo "${G} ${TODO} "`

NOTI=`cat ~/.notification`
NOTITEXT=`[ -z $NOTI ] || echo "${Y} ${NOTI} "`

MPC=`mpc current -f '%artist% - %title%' | sed 's/(.*)//g' | sed 's/\[.*\]//g'`
MPCTEXT="${B} ${MPC} "

VIM=`head -n 1 ~/.vimstatus`
VIMTEXT=`[ -z $VIM ] || echo "${Y} ${VIM} "`

TEMP0=`sysctl -n dev.cpu.0.temperature`
TEMP1=`sysctl -n dev.cpu.1.temperature`
TEMP2=`sysctl -n dev.cpu.2.temperature`
TEMP3=`sysctl -n dev.cpu.3.temperature`
TEMP=` cat << EOF | sort -r | head -n 1 | sed 's/\.[0-9]*C//'
$TEMP0
$TEMP1
$TEMP2
$TEMP3
EOF`
TEMPTEXT=`[ $TEMP -ge 90 ] && echo "${R} ${TEMP}C " || echo "${G} ${TEMP}C "`

echo "#[bg=#000000]${MPCTEXT}${VIMTEXT}${NOTITEXT}${TODOTEXT} ${TEMPTEXT} ${CHARGING} ${BATT}% ${CASSTIME}${TAUTEXT}"
