#!/bin/tcsh
set R = "#[fg=#ff4630]"
set Y = "#[fg=#ff9c30]"
set G = "#[fg=#30ff6a]"
set B = "#[fg=#3064ff]"
set D = "#[fg=#110c0f]"
set L = "#[fg=#334e4f]"
set BD = "#[bg=#110c0f]"

set level = (" " ▁ ▂ ▃ ▄ ▅ ▆ ▇ █)
set theme = ("$R" "$Y" "$G" "$B")
set day = `date +%j`
@ day = 1 + ($day % 4)
set T = "#[fg=#e36209]"

set mytime = `date +'%H:%M'`
setenv TZ "Asia/Manila"
set hertime = `date +'%H:%M'`
set herhour = `date +'%H'`

set night = "$T"
if ($herhour < 8) set night = "$D"

set vimstatus = `head -n 1 ~/.vimstatus`

set batt = `apm -l`
set battstate = `apm -b`

set temps = (`sysctl -n dev.cpu.0.temperature` \
`sysctl -n dev.cpu.1.temperature` \
`sysctl -n dev.cpu.2.temperature` \
`sysctl -n dev.cpu.3.temperature`)

set vol = `mixer vol | sed 's/.*:\([0-9]*\)$/\1/'`

set temp = 0
foreach t ($temps)
	set t = `echo $t | sed 's,\..C,,'`
	if ($temp < $t) @ temp = $t
end

set temperature = ""
set volume = ""
set battery = ""

foreach i (1 2 3 4 5 6 7 8 9)
	set n = 10
	@ n *= $i
	if ($temp >= $n) set temperature = $level[$i]
	if ($batt >= $n) set battery = $level[$i]
	if ($vol >= $n) set volume = $level[$i]
end

set mpctext = `mpc current -f '%file%' | sed -e 's/\[.*\]//g' -e 's/(.*)//g' -e 's/\.[a-z0-9]*$//' -e 's,/.* - [ ]*\(.*\)[ ]*$,/\1,'`
set status = (\
"$T" $mpctext "${L}$vimstatus" \
"$night$hertime" \
"$T$mytime" \
"$BD$temperature$volume$battery")

echo "$status"
