#!/bin/sh

DMENU="dmenu -l 12"

case $1 in
	"p")
		[ -n $2 ] && mpc -q clear && mpc -q load $2 && mpc -q play
		;;
	"pf")
		PL=`mpc ls | sort | uniq | fzy`
		mpc -q clear && mpc -q load "$PL" && mpc -q play
		;;
	"f")
		S=`mpc playl | sort | uniq | nl | fzy | sed 's,[ ]*\([0-9][0-9]*\).*,\1,'`
		mpc -q play "$S"
		;;
	"ls")
		mpc playl | sort | uniq | column
		;;
	"pl")
		mpc ls | sort | uniq | column
		;;
	*)
		mpc "`echo $@ | sed -e 's/^[a-z0-9-]* //' `" || echo "u wot m8"
		;;
esac
