#!/bin/tcsh
set R = "#[fg=#ff4630]"
set Y = "#[fg=#ff9c30]"
set G = "#[fg=#30ff6a]"
set B = "#[fg=#3064ff]"
set D = "#[fg=#110c0f]"
set L = "#[fg=#334e4f]"
set N = "#[fg=#000000]"

set T = "#[fg=#e36209]"

set panes = ("" _ "" _ "" _ "" _ "" _ "" _ "" _ "" _ "" _ "" _ "")

set i = $1
set j = $1
set k = $2
@ i = $i * 2 - 1
@ j = $i + 2
@ k = $k * 2 + 1
set panes[$i] = "$T"
set panes[$j] = "$D"
set panes[$k] = "$N"

echo "$D$panes"
